# Generated by Django 3.2.5 on 2021-07-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
